export const ActionTypes={
    ADD_TASK:"ADD_TASK",
    TASK_COMPLETED:"TASK_COMPLETED",
    SHOW_ACTIVE:"SHOW_ACTIVE",
    SHOW_COMPLETED:"SHOW_COMPLETED",
    SHOW_ALL:"SHOW_ALL",
    CHANGE_TASK_STATUS:"CHANGE_TASK_STATUS",
    REMOVE_TASK:"REMOVE_TASK"
}